spring.application.name=backend

# =========================
# BANCO DE DADOS LOCAL
# =========================

spring.datasource.url=jdbc:postgresql://localhost:5433/autoficha
spring.datasource.username=autoficha
spring.datasource.password=autoficha123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =========================
# JWT
# =========================

jwt.secret=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
jwt.expiration-ms=86400000


# =========================
# SERVIDOR
# =========================
